# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Classification.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1421, 1240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Import = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Import.setFont(font)
        self.Import.setObjectName("Import")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ImportButton = QtWidgets.QPushButton(self.tab)
        self.ImportButton.setObjectName("ImportButton")
        self.verticalLayout_2.addWidget(self.ImportButton)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Cluster_Label = QtWidgets.QLabel(self.groupBox)
        self.Cluster_Label.setObjectName("Cluster_Label")
        self.gridLayout.addWidget(self.Cluster_Label, 0, 2, 1, 1)
        self.Cluster_Slider = QtWidgets.QSlider(self.groupBox)
        self.Cluster_Slider.setMinimum(1)
        self.Cluster_Slider.setMaximum(10)
        self.Cluster_Slider.setPageStep(1)
        self.Cluster_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Cluster_Slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Cluster_Slider.setObjectName("Cluster_Slider")
        self.gridLayout.addWidget(self.Cluster_Slider, 0, 1, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.groupBox)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout.addWidget(self.StartButton, 1, 1, 1, 1)
        self.IterationsLable = QtWidgets.QLabel(self.groupBox)
        self.IterationsLable.setObjectName("IterationsLable")
        self.gridLayout.addWidget(self.IterationsLable, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OriginalImage = PlotWidget(self.groupBox_2)
        self.OriginalImage.setObjectName("OriginalImage")
        self.horizontalLayout.addWidget(self.OriginalImage)
        self.ClusterdImage = PlotWidget(self.groupBox_2)
        self.ClusterdImage.setObjectName("ClusterdImage")
        self.horizontalLayout.addWidget(self.ClusterdImage)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.Import.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ImportButtonSVM = QtWidgets.QPushButton(self.tab_2)
        self.ImportButtonSVM.setObjectName("ImportButtonSVM")
        self.gridLayout_3.addWidget(self.ImportButtonSVM, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ShowResult = QtWidgets.QPushButton(self.groupBox_6)
        self.ShowResult.setObjectName("ShowResult")
        self.horizontalLayout_4.addWidget(self.ShowResult)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OriginalImage_SVM = PlotWidget(self.groupBox_4)
        self.OriginalImage_SVM.setObjectName("OriginalImage_SVM")
        self.horizontalLayout_2.addWidget(self.OriginalImage_SVM)
        self.ClusterdImage_SVM = PlotWidget(self.groupBox_4)
        self.ClusterdImage_SVM.setObjectName("ClusterdImage_SVM")
        self.horizontalLayout_2.addWidget(self.ClusterdImage_SVM)
        self.gridLayout_3.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.Import.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ImportButtonSNN = QtWidgets.QPushButton(self.tab_3)
        self.ImportButtonSNN.setObjectName("ImportButtonSNN")
        self.verticalLayout_3.addWidget(self.ImportButtonSNN)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ShowResult_SNN = QtWidgets.QPushButton(self.groupBox_7)
        self.ShowResult_SNN.setObjectName("ShowResult_SNN")
        self.horizontalLayout_5.addWidget(self.ShowResult_SNN)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OriginalImage_SNN = PlotWidget(self.groupBox_5)
        self.OriginalImage_SNN.setObjectName("OriginalImage_SNN")
        self.horizontalLayout_3.addWidget(self.OriginalImage_SNN)
        self.ClusterdImage_SNN = PlotWidget(self.groupBox_5)
        self.ClusterdImage_SNN.setObjectName("ClusterdImage_SNN")
        self.horizontalLayout_3.addWidget(self.ClusterdImage_SNN)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.Import.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.Import)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Import.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pattern Recognition Midterm"))
        self.ImportButton.setText(_translate("MainWindow", "Import"))
        self.label_2.setText(_translate("MainWindow", "Number of clusters"))
        self.Cluster_Label.setText(_translate("MainWindow", "1"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.IterationsLable.setText(_translate("MainWindow", "iterations"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Images"))
        self.Import.setTabText(self.Import.indexOf(self.tab), _translate("MainWindow", "C - Means Classification"))
        self.ImportButtonSVM.setText(_translate("MainWindow", "Import"))
        self.ShowResult.setText(_translate("MainWindow", "Show Results"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Image"))
        self.Import.setTabText(self.Import.indexOf(self.tab_2), _translate("MainWindow", "SVM - Classification"))
        self.ImportButtonSNN.setText(_translate("MainWindow", "Import"))
        self.ShowResult_SNN.setText(_translate("MainWindow", "Show Results"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Image"))
        self.Import.setTabText(self.Import.indexOf(self.tab_3), _translate("MainWindow", "SNN - Classification"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
